//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMSEntities1 : DbContext
    {
        public IMSEntities1()
            : base("name=IMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutomobileCategory> AutomobileCategories { get; set; }
        public virtual DbSet<BuyPolicy> BuyPolicies { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<CustomerAgent> CustomerAgents { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PoliciesClaim> PoliciesClaims { get; set; }
        public virtual DbSet<PoliciesStatu> PoliciesStatus { get; set; }
        public virtual DbSet<PoliciesTransaction> PoliciesTransactions { get; set; }
        public virtual DbSet<PolicyCategory> PolicyCategories { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
