//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PolicyId { get; set; }
        public Nullable<long> carNumber { get; set; }
        public Nullable<short> expiryMonth { get; set; }
        public Nullable<short> expiryYear { get; set; }
        public Nullable<short> securityCode { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
