//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliciesTransaction
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> ActualPremiumDate { get; set; }
        public Nullable<System.DateTime> ActualPaymentDate { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual USER USER { get; set; }
    }
}
