//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliciesClaim
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<double> ClaimAmount { get; set; }
        public string RequiredDocuments { get; set; }
        public Nullable<int> ClaimStatusID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual PoliciesStatu PoliciesStatu { get; set; }
        public virtual USER USER { get; set; }
    }
}
